from_build: '19'
to_build: '38'

input_info:
  GCST90086057: # give the file a nickname
    file_in: '/project/ssverma_shared/projects/Ananya_CIS5200_CVD_Pred/GCST90086057_buildGRCh37.tsv.gz'
    chrCol: '1'
    posCol: '2'
    has_header: True
    keep_failed_rows: False

# usage:
# snakemake \
#   --snakefile /project/ssverma_shared/tools/lindsay_snakemake_workflows/liftover_wrapper/Snakefile \
#   --directory /project/ssverma_shared/tools/lindsay_snakemake_workflows/liftover_wrapper \
#   --configfile /project/ssverma_shared/projects/Ananya_CIS5200_CVD_Pred/config_liftover.yaml \
#   --cores 1 \
#   GCST90086057.liftover.tsv.gz