from_build: '19' # going from GRCh37/hg19
to_build: '38' # to GRCh38/hg38 (matches the format used in coherent data set so we can match up SNPs with effect sizes)

input_info:
  GCST90038595: # give the file a nickname
    file_in: '/project/ssverma_shared/projects/Ananya_CIS5200_CVD_Pred/GCST90038595_buildGRCh37.tsv.gz'
    chrCol: '2'
    posCol: '3'
    has_header: True
    keep_failed_rows: False

# usage:
# snakemake \
#   --snakefile /project/ssverma_shared/tools/lindsay_snakemake_workflows/liftover_wrapper/Snakefile \
#   --directory /project/ssverma_shared/projects/Ananya_CIS5200_CVD_Pred \
#   --configfile /project/ssverma_shared/projects/Ananya_CIS5200_CVD_Pred/config_liftover.yaml \
#   --cores 1 \
#   GCST90038595.liftover.tsv.gz